### PR TITLE
Made /run configurable

### PR DESCRIPTION
**Pull request by nomius**
Added option to configure --with-rootrun to make /run configurable.

### CODE REVIEW

**Comment by prologic** [comment]
+1

**Comment by blueness** [comment]
Yeah +1 one from me too.  I assume this is tested?  If so I'll commit.

**Comment by blueness** [comment]
Actually you missed the test.  Take a look at https://github.com/gentoo/eudev/pull/78.

**Comment by nomius** [comment]
Hi blueness, I think the patch is complete, please take a look at: https://github.com/nomius/eudev/blob/master/test/test-udev.c#L57
and https://github.com/nomius/eudev/blob/master/test/Makefile.am#L5

Thanks and best regards!

**Comment by blueness** [comment]
Okay I merges this but I did squash your two commits.  Please test and reopen if this is still a problem.

**Pull request closed without merging**
