### PR TITLE
Pavilion 13 x360 keys

### PR DESCRIPTION
**Pull request by MaxVerevkin**

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Is this repository dead?

**Comment by blueness** [comment]
No, not dead, I was just super busy for the last few weeks.  I'm finding time now to catch up.

This looks totally fine to me.  I may pull in a bunch of new definitions from upstream though which may cover this.  In the mean time, I'll commit this.

Again sorry for the delay.

**Comment by blueness** [comment]
pushed

**Comment by MaxVerevkin** [comment]
It's OK, understandable :)

**Pull request closed without merging**
